image: microsoft/dotnet:latest

variables:
  BUILD_CONFIGURATION: Debug

stages:
  - test
  - pack

test:
  stage: test
  script:
    - dotnet test AutoName.xUnit.Tests/

pack:
  stage: pack
  variables:
    PACK_PATH: $BUILD_CONFIGURATION
  script:
    - dotnet build AutoName.xUnit/
    - dotnet pack AutoName.xUnit/ -c $BUILD_CONFIGURATION -o $CI_PROJECT_DIR/$PACK_PATH

  artifacts:
    paths:
      - $PACK_PATH